# Generated by Django 2.2.28 on 2023-11-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_auto_20231109_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='type',
            new_name='provenance',
        ),
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(upload_to=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='disponibilite',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='photo',
            field=models.ImageField(upload_to=None, verbose_name=''),
        ),
    ]
