# Generated by Django 2.2.28 on 2023-11-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_auto_20231109_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(upload_to='static/images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='photo',
            field=models.ImageField(upload_to='static/images/', verbose_name=''),
        ),
    ]
