# Generated by Django 2.2.28 on 2023-11-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_auto_20231109_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='photo',
            field=models.CharField(max_length=100),
        ),
    ]
