# Generated by Django 2.2.28 on 2023-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_auto_20231111_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='photo',
            field=models.CharField(max_length=200),
        ),
    ]
