# Generated by Django 2.2.28 on 2023-11-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_auto_20231113_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
        migrations.RemoveField(
            model_name='character',
            name='provenance',
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(default='Pas de description', max_length=1000),
        ),
        migrations.AddField(
            model_name='equipement',
            name='description',
            field=models.CharField(default='Pas de description', max_length=1000),
        ),
        migrations.AddField(
            model_name='lieu',
            name='description',
            field=models.CharField(default='Pas de description', max_length=1000),
        ),
    ]
